# Generated by Django 2.0 on 2018-07-19 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('birthdays', '0002_auto_20180705_0458'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='birthday',
            options={'ordering': ['bday_name']},
        ),
    ]
